# Generated by Django 5.2.5 on 2025-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_resumepublic_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
