# Generated by Django 5.2.5 on 2025-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resumePublic',
            field=models.BooleanField(default=False),
        ),
    ]
