# Generated by Django 5.2.5 on 2025-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
