# Generated by Django 5.2.5 on 2025-08-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resumePublic',
        ),
    ]
