# Generated by Django 5.2.5 on 2025-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_resume_resumepublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
