# Generated by Django 5.2.5 on 2025-08-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_project_end_date_project_is_current_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingskill',
            old_name='skill_name',
            new_name='skill',
        ),
    ]
